version: "3"
services:
  site:
    container_name: "stugstatus"
    build: .
    ports:
      - "8036:5000"
    volumes:
      - data:/data
    environment:
      FLASK_API_KEY: "YOUR_KEY"
volumes:
  data:
